# Theme settings
dox:
    baseurl:
    title: Prohelion
    theme_color: '#232C3A' # Define theme primary color with HEX value
    language: en-US # Use ISO language and country codes to setup language of your website - https://www.w3schools.com/tags/ref_language_codes.asp and https://www.w3schools.com/tags/ref_country_codes.asp
    header:
        logo:
            text: 
            image: Prohelion_Title_Logo_Small.png
        nav:
            - item_name: Prohelion Website
              item_url: https://www.prohelion.com
        cta:
            label: Documentation Homepage
            url: /
            icon: book # Choose from 266 icons in "Feather" icon set, list of all icons is available here - https://feathericons.com
    footer:
        logo:
            text: Prohelion Documentation
            image:
        text: Copyright &copy; 2020. - Prohelion Pty Ltd <br>All rights reserved.
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your Disqus forum shortname to activate comments site-wide

# Defining collections
collections:
    documentation:
        output: true

# Defining defaults
defaults:
    -
        scope:
            path: ''
            type: 'documentation'
        values:
            layout: 'documentation-single'

# SASS settings
sass:
    sass_dir: ./dox-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./dox-theme/_layouts
includes_dir: ./dox-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
